In [1]:
# Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.
import numpy as np
x = np.arange(10, 22).reshape(3, 4)

# [[10 11 12 13]
# [14 15 16 17]
# [18 19 20 21]]
print(x)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [2]:
# Write a NumPy program to test whether none of the elements of a given array is zero.
import numpy as np
x = np.array([1, 2, 3, 4])

print("original array:")
print(x)
print("test if none of the elements of the said array is zero:")
# True
print(np.all(x))

x = np.array([0, 1, 2, 3])
print("original array:")
print(x)
print("test if none of the elements of the said array is zero:")
# False
print(np.all(x))


original array:
[1 2 3 4]
test if none of the elements of the said array is zero:
True
original array:
[0 1 2 3]
test if none of the elements of the said array is zero:
False


In [3]:
# Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array. 
import numpy as np
x = np.array([1, 7, 13, 105])

# 16 bytes
print("%d bytes" % (x.size * x.itemsize))


16 bytes


In [4]:
# Write a NumPy program to create an array of the integers from 30 to70
import numpy as np
array = np.arange(30, 71)

# [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
#  54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
print(array)


[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [5]:
# Write a NumPy program to reverse an array (first element becomes last).
import numpy as np
x = np.array([1, 2, 3, 4])

# [4 3 2 1]
print(np.flip(x))


[4 3 2 1]


In [6]:
# Write a NumPy program (using numpy) to sum of all the multiples of 3 or 5 below 100. 
import numpy as np
x = np.arange(1, 100)

# find  multiple of 3 or 5
n = x[(x % 3 == 0) | (x % 5 == 0)]
print(n[:1000])

# print sum the numbers
# [ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
#  54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
# 2318
print(n.sum())


[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [7]:
# Add the following two NumPy arrays and Modify a result array by calculating the square root of each element
import numpy as np
arrOne = np.array([[5, 6, 9], [21, 18, 27]])
arrTwo = np.array([[15, 33, 24], [4, 7, 1]])

result = arrOne + arrTwo
print(result)

for numbers in np.nditer(result, op_flags=['readwrite']):
    numbers[...] = numbers*numbers
print("result array after calculating the sqrt of all elements")
# [[ 400 1521 1089]
#  [ 625  625  784]]
print(result)


[[20 39 33]
 [25 25 28]]
result array after calculating the sqrt of all elements
[[ 400 1521 1089]
 [ 625  625  784]]


In [8]:
# Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10
import numpy as np
arr = np.arange(100, 200, 10)
arr = arr.reshape(5, 2)

# [[100 110]
#  [120 130]
#  [140 150]
#  [160 170]
#  [180 190]]
print(arr)


[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [9]:
# Following is the 2-D array. Print max from axis 0 and min from axis 1
import numpy as np
arr = np.array([[34,43,73],[82,22,12],[53,94,66]])

print("original array")
# [[34 43 73]
#  [82 22 12]
#  [53 94 66]]
print(arr)

minOfAxisxOne = np.amin(arr, 1)
print("amin of axis 1")
# [34 12 53]
print(minOfAxisxOne)

maxOfAxisOne = np.amax(arr, 0)
print("amax of axis 0")
# [82 94 73]
print(maxOfAxisOne)

original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
amin of axis 1
[34 12 53]
amax of axis 0
[82 94 73]


In [10]:
# Sort following NumPy array
import numpy as np
arr = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])

print("original array")
print(arr)

sortArrByRow = arr[:, arr[1, :].argsort()]
print("sort array by second row")
# [[73 43 34]
#  [12 22 82]
#  [66 94 53]]
print(sortArrByRow)

sortArrByColumn = arr[arr[:, 1].argsort()]
print("sort array by second column")
# [[82 22 12]
#  [34 43 73]
#  [53 94 66]]
print(sortArrByColumn)


original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
sort array by second row
[[73 43 34]
 [12 22 82]
 [66 94 53]]
sort array by second column
[[82 22 12]
 [34 43 73]
 [53 94 66]]
